apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: streaming
resources:
  - storage/pvcs.yaml
  - downloads/qbittorrent.yaml
  - downloads/qui.yaml
  - media-automation/prowlarr.yaml
  - media-automation/radarr.yaml
  - media-automation/sonarr.yaml
  # - media-server
  # - transcoding
  # - network
