apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cnpg-system
resources:
  - release-cert-manager.yaml
  - cloudflare-dns01-lasz-io-secret.yaml
  - cloudflare-dns01-lasz-io-issuer.yaml
