apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-operator.yaml
  - flux-instance.yaml
  - namespaces.yaml
  - gotk-sync.yaml
  - priority-classes.yaml
  - helm-repositories.yaml
