apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cilium
  namespace: kube-system
spec:
  chart: cilium
  repo: https://helm.cilium.io/
  targetNamespace: kube-system
  bootstrap: true
  valuesContent: |-
    routingMode: "native"
    ipv4NativeRoutingCIDR: 10.42.0.0/16
    autoDirectNodeRoutes: true
    
    # Force the kernel to know exactly where the pods are
    endpointRoutes:
      enabled: true

    bpf:
      masquerade: true
      hostRouting: true 
    enableIPv4Masquerade: true

    kubeProxyReplacement: true
    k8sServiceHost: 172.10.10.10
    k8sServicePort: 6443

    hostServices:
      enabled: true

    ipam:
      mode: "kubernetes"
    devices: "data0,net0,vpn0"
    directRoutingDevice: "data0"

    operator:
      replicas: 1
      tolerations:
        - operator: Exists
    tolerations:
      - operator: Exists

    cni:
      exclusive: false

    cgroup:
      autoMount:
        enabled: false
      hostRoot: /sys/fs/cgroup