apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: streaming
resources:
  - namespace.yaml
  - storage
  - downloads
  - media-automation
  - media-automation
  - media-automation
  - media-server
  - transcoding
  - network
