apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-media
  namespace: streaming
spec:
  storageClassName: tns-csi-nvmeof
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Ti
