---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-nginx-release
  namespace: flux-system
spec:
  interval: 5m
  path: ./k8s-manifests/infra/ingress-nginx/release
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
  timeout: 5m0s
  decryption:
    provider: sops
    secretRef:
      name: sops-age
