apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-prometheus-config
  namespace: lens-metrics
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }
    http {
      log_format json_combined escape=json
        '{'
          '"time_local":"$time_local",'
          '"remote_addr":"$remote_addr",'
          '"status": "$status",'
          '"request":"$request",'
          '"request_time":"$request_time"'
        '}';

      access_log /dev/stdout json_combined;

      server {
        listen 8080;

        location /healthz {
              access_log off;
              return 200;
        }

        # Pointing to the cross-namespace FQDN of your VM Cluster
        location / {
              proxy_set_header Host vm-cluster-vmselect.monitoring.svc.cluster.local;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              
              # Prepend the VM Cluster tenant prefix for Lens
              rewrite ^/(.*)$ /select/0/prometheus/$1 break;
              
              proxy_pass http://vm-cluster-vmselect.monitoring.svc.cluster.local:8481;
              proxy_read_timeout 90;
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-lens-proxy
  namespace: lens-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-lens-proxy
  template:
    metadata:
      labels:
        app: prometheus-lens-proxy
    spec:
      containers:
        - name: nginx
          image: nginx:stable-alpine
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
      volumes:
        - name: config
          configMap:
            name: nginx-prometheus-config
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: lens-metrics
  labels:
    app: prometheus
    component: server
spec:
  selector:
    app: prometheus-lens-proxy
  ports:
    - name: http
      port: 80
      targetPort: 8080