apiVersion: v1
kind: Secret
metadata:
    name: authentik-secrets
    namespace: auth
type: Opaque
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:AG9A/gmaq9/c+tDuDzxQF+Qd03LdCytcGjNY7UgyKAgGnVk6ijJ/RMGLYU2qxOYmUDE/+hYAVWgLvncKDmivYA==,iv:hNlz+ZnHTNxzZdle9cKEWFduqFEBN67AGhhFertxz6o=,tag:ym3Fe6wh/EFBz8EXRj6d6A==,type:str]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:5C2QlbjlcFoQztRBILILBjvAqzrSQwXco9rKjN+5KWdp31mUhkfTQ2S+DYmpGQ==,iv:2MjQImMzEh6P9oUhor8FIExrr7nysghzBLBaD9l+dVk=,tag:4elEuwXaBaYaGI8hq5QW6A==,type:str]
sops:
    age:
        - recipient: age1jyccg37m4ya4hmjynme83ye58zktx9qhagqwn8rc6zmh27s58fdsvclvu0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKWC91YnFtalNmMXNvazNn
            SjJuZHZwVGphTURUSWMzSmVrcTRlT2QwZEdJCjVWUXNKYlZaZlBtd3o5M0FDS2pR
            NEE4SE1aNS9RTkhIbjh1a3BjTnhTalUKLS0tIG9GTGt4MWNWalJkQmdwNDIrMXBr
            UXZlNUpaU242TlF4UnZXYktBY1lWU28K2rRRx1utNZBgPDxK7p+V3490cDyKDrsu
            rZ/miyDsxQKcHhbQkx4AEpG7g/AWOrEv51NlKI7D9iO30iVN5Cxx5Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1mg0cjjfnny5247jngl0hwwevyqgha3j4c6mhf5t9xucr6rl5qp2q334a22
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIVDZtUGp0bmR3SW1iWEtS
            TFpUc2s3ZlZEei9IMk16NEsvbFo0VTRwekNBCkZWUmdGRGJPODA4eDJYbFJqTHZH
            cGRMT0RlQ1c4dzVUc1ZUZXg0YjN2WmsKLS0tIExUVFMxckFYcFFGazM1bERFbEhP
            SnlTNHBvMUp6bndOZzRLL0RUMGxMWDQK/4oLtfSpuj7i9mB1XgJXfihR15uxdEvx
            jm7BhHkqytHD4bhNnNWdds+emz8J8F5oxeXgkgdsWzdJqgDXEJrUDQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1t9tzynl3lvld2xagkety02s4pzfntfwtswtddnqzes07dwn7evqqzze6lf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRSS9EK0NSSVBYdU5nNGx6
            bTBxMDZQMUd6YiswNGFQVEVVOVdmOGZSM3k0Ck8rUWpCVEU1aEFmMWQ5bVJPUVJ6
            b01xNnJxM2hYbWQ4YnZCZGkxVks5aTAKLS0tIHVXNExSSWlLd25vSHdjY2VGNzcz
            Um1KNlgrcXBZeXhDWlFKeC9HaDl3WFkKjyrFMRVOzcHQAWC0Of36AgqHkl+8UeI6
            AJkUY9JZ92t8+g9lO46MliaSVPXHaRmhOAksONf4J+ijsJiYyIsk5A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-28T17:25:45Z"
    mac: ENC[AES256_GCM,data:XlT+NZc8pSrYkR761jHZ3SwnFDf4wx0adBpm5+UGuL56I1Gl2Q7s/juzCmn4QI7zNHWlJ0gR6wiLZ06ZXy4JwkrFTy3U7nYskAXk8X4bfipZOfbC/kfV+gl6Phk1Cw615786BZBJYjZKMENrA83xhfiOYWIPMBMMNgSG5+tqQzc=,iv:5XIfrGxMkiro4AkoffVr2AU54z799jrsCr0bwT0Gqhc=,tag:9o8EORyLrD3po/h2XC0vJA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: authentik-postgresql-secret
    namespace: auth
type: Opaque
stringData:
    postgres-password: ENC[AES256_GCM,data:pTCoYP0/lvgRXy/t6cLq1MzBEYDwlWvotBiR1KGchjbfwx9htqyQctrekIkTXQ==,iv:MSRcD6N4GXNA9YhMmmriVmqBgljiOsy82IGmSv9EcLw=,tag:Rv8q8BBflph/Mk/wlb2obA==,type:str]
    password: ENC[AES256_GCM,data:30NOXkr4zkXpO5yIyKTUhXzoWFsls/Ji30KGK5ucUbPunqh11d1v65bBRT9MNA==,iv:fjHjBcl0+rTYtku0fbdOmTfXFh52HBQjJT7hSQ953VU=,tag:mWVWOChBotmfbQWDFkuOwQ==,type:str]
sops:
    age:
        - recipient: age1jyccg37m4ya4hmjynme83ye58zktx9qhagqwn8rc6zmh27s58fdsvclvu0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKWC91YnFtalNmMXNvazNn
            SjJuZHZwVGphTURUSWMzSmVrcTRlT2QwZEdJCjVWUXNKYlZaZlBtd3o5M0FDS2pR
            NEE4SE1aNS9RTkhIbjh1a3BjTnhTalUKLS0tIG9GTGt4MWNWalJkQmdwNDIrMXBr
            UXZlNUpaU242TlF4UnZXYktBY1lWU28K2rRRx1utNZBgPDxK7p+V3490cDyKDrsu
            rZ/miyDsxQKcHhbQkx4AEpG7g/AWOrEv51NlKI7D9iO30iVN5Cxx5Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1mg0cjjfnny5247jngl0hwwevyqgha3j4c6mhf5t9xucr6rl5qp2q334a22
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIVDZtUGp0bmR3SW1iWEtS
            TFpUc2s3ZlZEei9IMk16NEsvbFo0VTRwekNBCkZWUmdGRGJPODA4eDJYbFJqTHZH
            cGRMT0RlQ1c4dzVUc1ZUZXg0YjN2WmsKLS0tIExUVFMxckFYcFFGazM1bERFbEhP
            SnlTNHBvMUp6bndOZzRLL0RUMGxMWDQK/4oLtfSpuj7i9mB1XgJXfihR15uxdEvx
            jm7BhHkqytHD4bhNnNWdds+emz8J8F5oxeXgkgdsWzdJqgDXEJrUDQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1t9tzynl3lvld2xagkety02s4pzfntfwtswtddnqzes07dwn7evqqzze6lf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRSS9EK0NSSVBYdU5nNGx6
            bTBxMDZQMUd6YiswNGFQVEVVOVdmOGZSM3k0Ck8rUWpCVEU1aEFmMWQ5bVJPUVJ6
            b01xNnJxM2hYbWQ4YnZCZGkxVks5aTAKLS0tIHVXNExSSWlLd25vSHdjY2VGNzcz
            Um1KNlgrcXBZeXhDWlFKeC9HaDl3WFkKjyrFMRVOzcHQAWC0Of36AgqHkl+8UeI6
            AJkUY9JZ92t8+g9lO46MliaSVPXHaRmhOAksONf4J+ijsJiYyIsk5A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-28T17:25:45Z"
    mac: ENC[AES256_GCM,data:XlT+NZc8pSrYkR761jHZ3SwnFDf4wx0adBpm5+UGuL56I1Gl2Q7s/juzCmn4QI7zNHWlJ0gR6wiLZ06ZXy4JwkrFTy3U7nYskAXk8X4bfipZOfbC/kfV+gl6Phk1Cw615786BZBJYjZKMENrA83xhfiOYWIPMBMMNgSG5+tqQzc=,iv:5XIfrGxMkiro4AkoffVr2AU54z799jrsCr0bwT0Gqhc=,tag:9o8EORyLrD3po/h2XC0vJA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: authentik-redis-secret
    namespace: auth
type: Opaque
stringData:
    redis-password: ENC[AES256_GCM,data:BBuTQEppvN+WV2k13KLrM7dTOUrUbxMyqQ4tGLC1to95fotvlpdjHqpGgz+W9A==,iv:kw073SO5oRBZXGYa/tHY3N1YR1Y0DtIFH8kF0HEaCs8=,tag:r0GWLE0JTt+aeVTH/Zig6Q==,type:str]
sops:
    age:
        - recipient: age1jyccg37m4ya4hmjynme83ye58zktx9qhagqwn8rc6zmh27s58fdsvclvu0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKWC91YnFtalNmMXNvazNn
            SjJuZHZwVGphTURUSWMzSmVrcTRlT2QwZEdJCjVWUXNKYlZaZlBtd3o5M0FDS2pR
            NEE4SE1aNS9RTkhIbjh1a3BjTnhTalUKLS0tIG9GTGt4MWNWalJkQmdwNDIrMXBr
            UXZlNUpaU242TlF4UnZXYktBY1lWU28K2rRRx1utNZBgPDxK7p+V3490cDyKDrsu
            rZ/miyDsxQKcHhbQkx4AEpG7g/AWOrEv51NlKI7D9iO30iVN5Cxx5Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1mg0cjjfnny5247jngl0hwwevyqgha3j4c6mhf5t9xucr6rl5qp2q334a22
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIVDZtUGp0bmR3SW1iWEtS
            TFpUc2s3ZlZEei9IMk16NEsvbFo0VTRwekNBCkZWUmdGRGJPODA4eDJYbFJqTHZH
            cGRMT0RlQ1c4dzVUc1ZUZXg0YjN2WmsKLS0tIExUVFMxckFYcFFGazM1bERFbEhP
            SnlTNHBvMUp6bndOZzRLL0RUMGxMWDQK/4oLtfSpuj7i9mB1XgJXfihR15uxdEvx
            jm7BhHkqytHD4bhNnNWdds+emz8J8F5oxeXgkgdsWzdJqgDXEJrUDQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1t9tzynl3lvld2xagkety02s4pzfntfwtswtddnqzes07dwn7evqqzze6lf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRSS9EK0NSSVBYdU5nNGx6
            bTBxMDZQMUd6YiswNGFQVEVVOVdmOGZSM3k0Ck8rUWpCVEU1aEFmMWQ5bVJPUVJ6
            b01xNnJxM2hYbWQ4YnZCZGkxVks5aTAKLS0tIHVXNExSSWlLd25vSHdjY2VGNzcz
            Um1KNlgrcXBZeXhDWlFKeC9HaDl3WFkKjyrFMRVOzcHQAWC0Of36AgqHkl+8UeI6
            AJkUY9JZ92t8+g9lO46MliaSVPXHaRmhOAksONf4J+ijsJiYyIsk5A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-28T17:25:45Z"
    mac: ENC[AES256_GCM,data:XlT+NZc8pSrYkR761jHZ3SwnFDf4wx0adBpm5+UGuL56I1Gl2Q7s/juzCmn4QI7zNHWlJ0gR6wiLZ06ZXy4JwkrFTy3U7nYskAXk8X4bfipZOfbC/kfV+gl6Phk1Cw615786BZBJYjZKMENrA83xhfiOYWIPMBMMNgSG5+tqQzc=,iv:5XIfrGxMkiro4AkoffVr2AU54z799jrsCr0bwT0Gqhc=,tag:9o8EORyLrD3po/h2XC0vJA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: geoip-secrets
    namespace: auth
type: Opaque
stringData:
    account_id: ENC[AES256_GCM,data:ybhBWdYUOg==,iv:evBuKlqHT4fPj1tVC4cmOJoxvkO1US0yDvwcvx5Ps/I=,tag:ze7wN7blBZKMBWAm8a/L2w==,type:str]
    license_key: ENC[AES256_GCM,data:PnXs1P5XcXL75CNzV/HbBXFs2sDYxCjAL476jclfeFl/9nhUZQOvyw==,iv:ig3TbTM53fYXoHGggojM/LeX7/z+fYI1Iyz0u5nnLY4=,tag:3P5fwQShMs2AIAErPq+d6Q==,type:str]
sops:
    age:
        - recipient: age1jyccg37m4ya4hmjynme83ye58zktx9qhagqwn8rc6zmh27s58fdsvclvu0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKWC91YnFtalNmMXNvazNn
            SjJuZHZwVGphTURUSWMzSmVrcTRlT2QwZEdJCjVWUXNKYlZaZlBtd3o5M0FDS2pR
            NEE4SE1aNS9RTkhIbjh1a3BjTnhTalUKLS0tIG9GTGt4MWNWalJkQmdwNDIrMXBr
            UXZlNUpaU242TlF4UnZXYktBY1lWU28K2rRRx1utNZBgPDxK7p+V3490cDyKDrsu
            rZ/miyDsxQKcHhbQkx4AEpG7g/AWOrEv51NlKI7D9iO30iVN5Cxx5Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1mg0cjjfnny5247jngl0hwwevyqgha3j4c6mhf5t9xucr6rl5qp2q334a22
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIVDZtUGp0bmR3SW1iWEtS
            TFpUc2s3ZlZEei9IMk16NEsvbFo0VTRwekNBCkZWUmdGRGJPODA4eDJYbFJqTHZH
            cGRMT0RlQ1c4dzVUc1ZUZXg0YjN2WmsKLS0tIExUVFMxckFYcFFGazM1bERFbEhP
            SnlTNHBvMUp6bndOZzRLL0RUMGxMWDQK/4oLtfSpuj7i9mB1XgJXfihR15uxdEvx
            jm7BhHkqytHD4bhNnNWdds+emz8J8F5oxeXgkgdsWzdJqgDXEJrUDQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1t9tzynl3lvld2xagkety02s4pzfntfwtswtddnqzes07dwn7evqqzze6lf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRSS9EK0NSSVBYdU5nNGx6
            bTBxMDZQMUd6YiswNGFQVEVVOVdmOGZSM3k0Ck8rUWpCVEU1aEFmMWQ5bVJPUVJ6
            b01xNnJxM2hYbWQ4YnZCZGkxVks5aTAKLS0tIHVXNExSSWlLd25vSHdjY2VGNzcz
            Um1KNlgrcXBZeXhDWlFKeC9HaDl3WFkKjyrFMRVOzcHQAWC0Of36AgqHkl+8UeI6
            AJkUY9JZ92t8+g9lO46MliaSVPXHaRmhOAksONf4J+ijsJiYyIsk5A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-28T17:25:45Z"
    mac: ENC[AES256_GCM,data:XlT+NZc8pSrYkR761jHZ3SwnFDf4wx0adBpm5+UGuL56I1Gl2Q7s/juzCmn4QI7zNHWlJ0gR6wiLZ06ZXy4JwkrFTy3U7nYskAXk8X4bfipZOfbC/kfV+gl6Phk1Cw615786BZBJYjZKMENrA83xhfiOYWIPMBMMNgSG5+tqQzc=,iv:5XIfrGxMkiro4AkoffVr2AU54z799jrsCr0bwT0Gqhc=,tag:9o8EORyLrD3po/h2XC0vJA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
