apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent-vpn-credentials
    namespace: streaming
type: Opaque
stringData:
    openvpn-user: ENC[AES256_GCM,data:WwTe6+Y3NMz1WRgpukWVsAVJ2Jo=,iv:7I0YHW9FNfAccwgVO+E8P+6t975q4nPfibzTZHjvXlU=,tag:3i6FcW/MLwzTL8BMyAI7Gg==,type:str]
    openvpn-password: ENC[AES256_GCM,data:sCXhoceiM+4mBEX5Ue5c9AyeDCjpXTfzPPFbXxkdvgw=,iv:dRjPLfb0qGF94KP7MuxzbWVIL6y7WMtQ5Eye8fPrbxo=,tag:qLKA4d9g5sO7CfxUVD6Icg==,type:str]
sops:
    age:
        - recipient: age1jyccg37m4ya4hmjynme83ye58zktx9qhagqwn8rc6zmh27s58fdsvclvu0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6MHJiMzg3MGV6c3BKYk9F
            eGgzQ1Q5a3pPeXoyaWV3NnovMWZtbUQ2SFFrClFEVUdzTzB0U1pubXBCd2JpZnBR
            ME1TVUtweFRUck13QUYwdkJ5Y01UdzAKLS0tIGxYaHNVWSt2NFJXQ2YyQzVMcVhP
            V0xKNjFKMUFvSWtNa213SFN6RktHajAKVM8pL8ckwmCNGAceLIvZX1C5H5exxkxl
            fzE1tovs3Dfaq5F3wLaL43tMY/v14yi5Q2XOPyhaOwq8dgD3hxtzZw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1mg0cjjfnny5247jngl0hwwevyqgha3j4c6mhf5t9xucr6rl5qp2q334a22
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSWmxBY2RONjRVQ3g3ZTNX
            Vk9pejhvaU9oZ0RhN1BNR0hGc2ZadFZ3ZUQ0CnhQSXVvbWVpL3YwQ29hREFwUDVH
            SFBhRDFLSWN4cU5VNXYrOVZwMlJkQXcKLS0tIHduT2lqMTRFQy9sMmtpemR0SzdM
            TjBOdzBpcVppMVJwR3VBQmJzakFDZEUKVZDCGremJbaGhbhWGh3wldPbkwTbG7Kp
            kyv7Z4tA+1wy8e0Ym8gF1S1jUWiOaWqQq76cFRpBBRRr7CITfSnONQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1t9tzynl3lvld2xagkety02s4pzfntfwtswtddnqzes07dwn7evqqzze6lf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDblJCamlIVHZkbXFzRFNk
            c1Y2REhYdUVFdkV1UE8zL0owTElHNmhMekJVCklUWjVwcjRsWkg5QklmNSt6bW5y
            V0o3aHh6dnJzSWRYdW9JWnY0Z3M4c00KLS0tIGNvR0FweEpaTVl2VkJsTTBEWUoz
            bjMrdnlKTzRZZWNYZ013V0VQT2p3TEUKk4QTrxlAHocfTemd72YafM78E+sfWIg1
            oNcDPOfGrmefQCclCVFgj2/wSRg7H6oI7ZTNs8ktEVD1eW8kH690YQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-30T19:04:45Z"
    mac: ENC[AES256_GCM,data:vci1Oyb+Mvx6c9ROMhpXFCzyM5J4IvI46RGW/SYU5klpcEhFy4u840mcvPRqi9YBlpgTwermwTlhNfu/Shf2jQyX5yt6Ct3fdb3RVURjj5XaB2URbRNv4X+VgNlKWKBwT1W9+Oz/+ITcrRyo2siXeINoBSYu7sogmFTiy2NlznU=,iv:s0sSfyWJf5TLWX8QmwhBmgKAsGrPahLdQKkZWQjAMXc=,tag:Ni9N+RYjQ2Sg4cnc6R6yQw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
