apiVersion: v1
kind: Secret
metadata:
    name: authentik-secrets
    namespace: auth
type: Opaque
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:wEg6MhYQOO0hQ7ba6yiuiLdrOImUVrED5iin5MqJp6bh/f34FrBN81rgMXQ69wfE0YstetK34FW+58JwjRXRuA==,iv:9ZZ4iauHDTrYxEIxIBVew1AAiKOI7d0gD5Krd1qc3YA=,tag:GV8rxSjVPL7vA7DsCurgFw==,type:str]
    AUTHENTIK_POSTGRESQL__HOST: ENC[AES256_GCM,data:nDRb2+JKfW2TM4oqToXKmxwsObk=,iv:3irvDZrhYBfAKi64BmgllzR8XYLlu7MshtQ4jDhVUzY=,tag:x8649sx+22TPD5QtT1cJxw==,type:str]
    AUTHENTIK_POSTGRESQL__NAME: ENC[AES256_GCM,data:lnZ2AxscVrRV,iv:JCmpzmoSIYHkuVAi3eA/Uk7ha6HE6atakgwxwt/7/CQ=,tag:dpTKbPJF6dnxgIs8meC3NQ==,type:str]
    AUTHENTIK_POSTGRESQL__USER: ENC[AES256_GCM,data:jRU1rXzUoRZ0,iv:PBwjKdloiuBTRD3BWg9KNDQpaLB/qNF/uwzITVsa6dE=,tag:iaUGsSoYB/dbxWs2SbXsYA==,type:str]
    AUTHENTIK_POSTGRESQL__PORT: ENC[AES256_GCM,data:qZMbxg==,iv:rHWzKTZi8sL20UnMkn72Z0nF8A7QdNQLzoO6174ft80=,tag:IRoBwArQPbh1QynO/47QRQ==,type:str]
    AUTHENTIK_REDIS__HOST: ENC[AES256_GCM,data:XZYH/bK/+bsU3rBrxUAcehcw2KUeGg==,iv:Thr5J3YJssL81fkEPy3E9hpaxgogrZMqCaYnMMzVUg8=,tag:5BpB4rqdfMzAuoQG+7bnKQ==,type:str]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:tWPpDcqJSeQ7s1KDF9W/In5jP4y87PLQZmRqq5LZC83T2Ag23DhGlGO+kMyi+A==,iv:10hLbye9R1qy56MijSBhIA9RS9INjP5wdobEkROA3T0=,tag:QjOAjFV3lG+A+MVvCw3j+Q==,type:str]
    AUTHENTIK_REDIS__PASSWORD: ENC[AES256_GCM,data:d3ITFXFG/CPrIN4wkCaFlP0vWtQMAuHrIBtbxU1/53baT1MDv/NWWth6VNDgtQ==,iv:IEmnzdlTCDrjgrOj6WoVxj651RAcszfXigzMxfd2FqM=,tag:BCvymz8toaBRFv6S6gCKlg==,type:str]
sops:
    age:
        - recipient: age1jyccg37m4ya4hmjynme83ye58zktx9qhagqwn8rc6zmh27s58fdsvclvu0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBycFlCK2wzZEwvNnA5b0sx
            TTBoSncvbkhaT1JXWExuS3RHMFUwSUV2YXlrCkhGVWZPeDlSbHIxb2d5cnk2K1BU
            MmtXWVRKMFZpZytBTFlZcGpZUk55eHcKLS0tIFppRnYyTGg5OCtSZ1pWUml6TFNQ
            d1ZRczNVNE9wNHl2VDUxQllXanNvZ00KJVlfuCPq0CxXcR9W1/sTAgYAKdR4DQfv
            M4+7o0xOC7FO1E6yFzsxrL7W5bAaSCQ/S63yju6Jqn+y2MswpRt6wA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1mg0cjjfnny5247jngl0hwwevyqgha3j4c6mhf5t9xucr6rl5qp2q334a22
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTVBWRzY1ZzVhdXVPSm1y
            TW5QZmpPL3VTV1JDeEFJUWViUHFKUWRaWXdVCmI4aFppd3lWMmlIVlNzeDl4MUhC
            VUZORnA1cEpkLysrR29kVnUvK2tyeWsKLS0tIEN2enNlWjBnMWxObnFEdmlkZ1RM
            MW5VYU9wazRib013NzFqTkR5ek84U2cK+dYuaB+vNq2iCGyz7a35PEc+dlrR1xsW
            R5sgrhOV5qEPwIbfZvOumW0GPgtUzFjBH7uCZxmX1GzFAFPa9f47Tg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1t9tzynl3lvld2xagkety02s4pzfntfwtswtddnqzes07dwn7evqqzze6lf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3U21qTkRIQTVDK2xkaXFZ
            TDVpdUlLdWt4WnpTUjVubFlMSk40YUpoSXlVCkJYc2tHeUNENUw3WjlodXorNE5k
            YnZYSWRPclFweGJYWHBTRFdRODJzeUkKLS0tIEN5bHJnMjFQZW92Tk5NZkYzOXQ1
            ZzdYT3NpV2FpanpxL002ZEEyTklhOEkKtA/KuWRlNpbtfgxXdgeEuPwZgHoodPM8
            cwm9jLd/Dec+UksoiLUliWTtjnlUwKl3fNq/7314YfGz13fNJBN5AA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-28T17:50:41Z"
    mac: ENC[AES256_GCM,data:j9mWOI3+eFhO+2rQQ5aRs2wtvhkJMJH+ysZsdWXknIeSq3+eqdQz+Rkl8Xg+O7RAhfJJPeHnj7Vg9dvyiSDb5EVZznx8ChGM6tseEHMa8qxTDPC3lcWefGbVT2m0JgmTh7aveGjEWJaRNm+A5qjBey8EIq83CCUZjQlT9Kc6dEA=,iv:pWpmM2GaGZu+A84VcRj/Ou1G8+k2I/Ekql9gam9AAgk=,tag:wv1YVqShPJWfD67b6uvgzg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: authentik-postgresql-secret
    namespace: auth
type: Opaque
stringData:
    postgres-password: ENC[AES256_GCM,data:YDpIN56syJiBU0ClIK+SN8oaY7f3afwrKvJTOj/UaP8lnXECHuUHHfA18x+wrA==,iv:Ov5VW830JPnnflTMU2BfJq4vObqzAqTUOF+KuG5MMUI=,tag:ITFdBAAaBfC/dKVbwZjh8Q==,type:str]
    password: ENC[AES256_GCM,data:+c+vxxMfLiAnvxeFTG3QOo8qJ3HuHIARYgLx2IpVbq7CTjPsahQpoR025n2+8g==,iv:kR+ihgVqaGRYW0qfLQL0wLmnEBpoGIlv/RgvigTirC8=,tag:6N4SqgJSGCBFk5JPnYQmlg==,type:str]
sops:
    age:
        - recipient: age1jyccg37m4ya4hmjynme83ye58zktx9qhagqwn8rc6zmh27s58fdsvclvu0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBycFlCK2wzZEwvNnA5b0sx
            TTBoSncvbkhaT1JXWExuS3RHMFUwSUV2YXlrCkhGVWZPeDlSbHIxb2d5cnk2K1BU
            MmtXWVRKMFZpZytBTFlZcGpZUk55eHcKLS0tIFppRnYyTGg5OCtSZ1pWUml6TFNQ
            d1ZRczNVNE9wNHl2VDUxQllXanNvZ00KJVlfuCPq0CxXcR9W1/sTAgYAKdR4DQfv
            M4+7o0xOC7FO1E6yFzsxrL7W5bAaSCQ/S63yju6Jqn+y2MswpRt6wA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1mg0cjjfnny5247jngl0hwwevyqgha3j4c6mhf5t9xucr6rl5qp2q334a22
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTVBWRzY1ZzVhdXVPSm1y
            TW5QZmpPL3VTV1JDeEFJUWViUHFKUWRaWXdVCmI4aFppd3lWMmlIVlNzeDl4MUhC
            VUZORnA1cEpkLysrR29kVnUvK2tyeWsKLS0tIEN2enNlWjBnMWxObnFEdmlkZ1RM
            MW5VYU9wazRib013NzFqTkR5ek84U2cK+dYuaB+vNq2iCGyz7a35PEc+dlrR1xsW
            R5sgrhOV5qEPwIbfZvOumW0GPgtUzFjBH7uCZxmX1GzFAFPa9f47Tg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1t9tzynl3lvld2xagkety02s4pzfntfwtswtddnqzes07dwn7evqqzze6lf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3U21qTkRIQTVDK2xkaXFZ
            TDVpdUlLdWt4WnpTUjVubFlMSk40YUpoSXlVCkJYc2tHeUNENUw3WjlodXorNE5k
            YnZYSWRPclFweGJYWHBTRFdRODJzeUkKLS0tIEN5bHJnMjFQZW92Tk5NZkYzOXQ1
            ZzdYT3NpV2FpanpxL002ZEEyTklhOEkKtA/KuWRlNpbtfgxXdgeEuPwZgHoodPM8
            cwm9jLd/Dec+UksoiLUliWTtjnlUwKl3fNq/7314YfGz13fNJBN5AA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-28T17:50:41Z"
    mac: ENC[AES256_GCM,data:j9mWOI3+eFhO+2rQQ5aRs2wtvhkJMJH+ysZsdWXknIeSq3+eqdQz+Rkl8Xg+O7RAhfJJPeHnj7Vg9dvyiSDb5EVZznx8ChGM6tseEHMa8qxTDPC3lcWefGbVT2m0JgmTh7aveGjEWJaRNm+A5qjBey8EIq83CCUZjQlT9Kc6dEA=,iv:pWpmM2GaGZu+A84VcRj/Ou1G8+k2I/Ekql9gam9AAgk=,tag:wv1YVqShPJWfD67b6uvgzg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: authentik-redis-secret
    namespace: auth
type: Opaque
stringData:
    redis-password: ENC[AES256_GCM,data:U5GVk/L2ZjB9/628yq+FNwEwHmvCSfu2pYrWEXPXNZVrt6j4Ihs7yPwqg9pjSQ==,iv:lcx4BjBrMbMA3qcFX387fuqsqM2ZyqcHBisKLeIJKQA=,tag:dJTAeKI5gXCSI+W+/dng9g==,type:str]
sops:
    age:
        - recipient: age1jyccg37m4ya4hmjynme83ye58zktx9qhagqwn8rc6zmh27s58fdsvclvu0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBycFlCK2wzZEwvNnA5b0sx
            TTBoSncvbkhaT1JXWExuS3RHMFUwSUV2YXlrCkhGVWZPeDlSbHIxb2d5cnk2K1BU
            MmtXWVRKMFZpZytBTFlZcGpZUk55eHcKLS0tIFppRnYyTGg5OCtSZ1pWUml6TFNQ
            d1ZRczNVNE9wNHl2VDUxQllXanNvZ00KJVlfuCPq0CxXcR9W1/sTAgYAKdR4DQfv
            M4+7o0xOC7FO1E6yFzsxrL7W5bAaSCQ/S63yju6Jqn+y2MswpRt6wA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1mg0cjjfnny5247jngl0hwwevyqgha3j4c6mhf5t9xucr6rl5qp2q334a22
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTVBWRzY1ZzVhdXVPSm1y
            TW5QZmpPL3VTV1JDeEFJUWViUHFKUWRaWXdVCmI4aFppd3lWMmlIVlNzeDl4MUhC
            VUZORnA1cEpkLysrR29kVnUvK2tyeWsKLS0tIEN2enNlWjBnMWxObnFEdmlkZ1RM
            MW5VYU9wazRib013NzFqTkR5ek84U2cK+dYuaB+vNq2iCGyz7a35PEc+dlrR1xsW
            R5sgrhOV5qEPwIbfZvOumW0GPgtUzFjBH7uCZxmX1GzFAFPa9f47Tg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1t9tzynl3lvld2xagkety02s4pzfntfwtswtddnqzes07dwn7evqqzze6lf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3U21qTkRIQTVDK2xkaXFZ
            TDVpdUlLdWt4WnpTUjVubFlMSk40YUpoSXlVCkJYc2tHeUNENUw3WjlodXorNE5k
            YnZYSWRPclFweGJYWHBTRFdRODJzeUkKLS0tIEN5bHJnMjFQZW92Tk5NZkYzOXQ1
            ZzdYT3NpV2FpanpxL002ZEEyTklhOEkKtA/KuWRlNpbtfgxXdgeEuPwZgHoodPM8
            cwm9jLd/Dec+UksoiLUliWTtjnlUwKl3fNq/7314YfGz13fNJBN5AA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-28T17:50:41Z"
    mac: ENC[AES256_GCM,data:j9mWOI3+eFhO+2rQQ5aRs2wtvhkJMJH+ysZsdWXknIeSq3+eqdQz+Rkl8Xg+O7RAhfJJPeHnj7Vg9dvyiSDb5EVZznx8ChGM6tseEHMa8qxTDPC3lcWefGbVT2m0JgmTh7aveGjEWJaRNm+A5qjBey8EIq83CCUZjQlT9Kc6dEA=,iv:pWpmM2GaGZu+A84VcRj/Ou1G8+k2I/Ekql9gam9AAgk=,tag:wv1YVqShPJWfD67b6uvgzg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: geoip-secrets
    namespace: auth
type: Opaque
stringData:
    account_id: ENC[AES256_GCM,data:Vt4ej7xRbQ==,iv:dSB4zl7XqlryGlKKgG8t6eVlppsFS4XXPVPAA3OWyAU=,tag:Y/ncYAtjOgqh/sOft8cvvg==,type:str]
    license_key: ENC[AES256_GCM,data:3puLN7uuklUib2TPoV0L1s3PVM/XhJ0smxUwRiRxHvthu/Fxhbpz1g==,iv:p+1h0JafD2ouzH/2c+9SttCfGi2Xnyi8vgl4MNfkOGI=,tag:m5Lw+36AIwUBEPfyQsRLNg==,type:str]
sops:
    age:
        - recipient: age1jyccg37m4ya4hmjynme83ye58zktx9qhagqwn8rc6zmh27s58fdsvclvu0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBycFlCK2wzZEwvNnA5b0sx
            TTBoSncvbkhaT1JXWExuS3RHMFUwSUV2YXlrCkhGVWZPeDlSbHIxb2d5cnk2K1BU
            MmtXWVRKMFZpZytBTFlZcGpZUk55eHcKLS0tIFppRnYyTGg5OCtSZ1pWUml6TFNQ
            d1ZRczNVNE9wNHl2VDUxQllXanNvZ00KJVlfuCPq0CxXcR9W1/sTAgYAKdR4DQfv
            M4+7o0xOC7FO1E6yFzsxrL7W5bAaSCQ/S63yju6Jqn+y2MswpRt6wA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1mg0cjjfnny5247jngl0hwwevyqgha3j4c6mhf5t9xucr6rl5qp2q334a22
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTVBWRzY1ZzVhdXVPSm1y
            TW5QZmpPL3VTV1JDeEFJUWViUHFKUWRaWXdVCmI4aFppd3lWMmlIVlNzeDl4MUhC
            VUZORnA1cEpkLysrR29kVnUvK2tyeWsKLS0tIEN2enNlWjBnMWxObnFEdmlkZ1RM
            MW5VYU9wazRib013NzFqTkR5ek84U2cK+dYuaB+vNq2iCGyz7a35PEc+dlrR1xsW
            R5sgrhOV5qEPwIbfZvOumW0GPgtUzFjBH7uCZxmX1GzFAFPa9f47Tg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1t9tzynl3lvld2xagkety02s4pzfntfwtswtddnqzes07dwn7evqqzze6lf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3U21qTkRIQTVDK2xkaXFZ
            TDVpdUlLdWt4WnpTUjVubFlMSk40YUpoSXlVCkJYc2tHeUNENUw3WjlodXorNE5k
            YnZYSWRPclFweGJYWHBTRFdRODJzeUkKLS0tIEN5bHJnMjFQZW92Tk5NZkYzOXQ1
            ZzdYT3NpV2FpanpxL002ZEEyTklhOEkKtA/KuWRlNpbtfgxXdgeEuPwZgHoodPM8
            cwm9jLd/Dec+UksoiLUliWTtjnlUwKl3fNq/7314YfGz13fNJBN5AA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-28T17:50:41Z"
    mac: ENC[AES256_GCM,data:j9mWOI3+eFhO+2rQQ5aRs2wtvhkJMJH+ysZsdWXknIeSq3+eqdQz+Rkl8Xg+O7RAhfJJPeHnj7Vg9dvyiSDb5EVZznx8ChGM6tseEHMa8qxTDPC3lcWefGbVT2m0JgmTh7aveGjEWJaRNm+A5qjBey8EIq83CCUZjQlT9Kc6dEA=,iv:pWpmM2GaGZu+A84VcRj/Ou1G8+k2I/Ekql9gam9AAgk=,tag:wv1YVqShPJWfD67b6uvgzg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
