apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:peEBWBzeWY3i3JL12Sm3lisuPjrfpNGdzTNLnP0oTlqJETl0K2WaSA==,iv:bmn0a/4LH8TcuKC7GoOiHK7p9iRhh2MthuIAwosa594=,tag:Hl20MCJITMD8vL4pFUJx3w==,type:str]
sops:
    age:
        - recipient: age1jyccg37m4ya4hmjynme83ye58zktx9qhagqwn8rc6zmh27s58fdsvclvu0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWbHRMWXZsTDBBb045djFa
            bE1abFZSNmFBVHczeitOZWxzOURqV2tGMVNJCjVzeHU1MkJmb0ltMHhJbVp5Ymtj
            QkJDbEFqUjB3U0w4ODlpSjAzVG9FV1EKLS0tIDVwcWw1cy8yT0g5ZTVvOEhsMTFB
            aUVwSHBrSzN2ZmpkOUk1c2VlWlNvMGcKG+75eI/2r4zYZwHbTLaKExbJ0D/rlAO8
            J0iEzsmPPDMQ0CbN5jJ2XO/0cNyyvqqo3C4da2aavsC4Q5vmief+XQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1mg0cjjfnny5247jngl0hwwevyqgha3j4c6mhf5t9xucr6rl5qp2q334a22
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYUEEyTGRsQnpPWXdmcy9t
            b3FGKzU2eHV3TWRTam5xZ2hNeW9BbjZ4Tld3CmpyY1orYnRVNVN1WkJ0WGpVb3Iv
            QXFqNGozVlZQYnpQaVBveVVYNzlQRUUKLS0tIFZzVzBLTHl6cWU5b3FtajFuS3A2
            d3U0bHE0Mm1GYTJrOUQzeEthd3FwRDAK2UXq4D+da6zAAL25CRiTpBED6xUTnChb
            xhlM5awn8nqzRSJAATzbIFrpigb1vw1/NnHiw9+di6kDrg9+OPwKGA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1t9tzynl3lvld2xagkety02s4pzfntfwtswtddnqzes07dwn7evqqzze6lf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMcjNpM3ZiN0xleUdmaFNo
            YUhnajVweGNVQUdWd3d1ZFZhcHpYVnkzU0J3CnVIam9xZG84N0kwdXlDQ0hicGY5
            RW81bzQ3TE5HQ21DNGIyS1ZidEI4d2MKLS0tIGs2RVJicHRIN1AwdjR3b3ZVeGkr
            dklXZkF0b1RBL1Y2Y2hZYzJBSXhkZ1EKYPkEIvbFxKztdHPH+QYGTBTBHQhzPSBC
            s3o2I++5Dvh4xwUK3Mdn9TXRTVkmF9IQfDkeWUyVOTHw3/ivlnE5NQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T22:10:01Z"
    mac: ENC[AES256_GCM,data:UJKd316cbxzfIkmKDj9SykfcZHjX0uVmOb3k8lnAh6YVTkKBigXI6x1CPawYVdYRqvnQ0wlF7Zk1lm2zb8PnU5vHSF8HCAsRexmmFneIlzIy2C4Mm/oe4pHhD0jBwxBTlNQnBm46T/k36zdn/UZTjsvDt8hfDebShHrS41RCaSs=,iv:gz4xMpdSo2+r9+Kn3jVMp0YrQySqMYDREZbZdV+qKN8=,tag:M2FIW+yliOJj2qkNg6WZFA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
