apiVersion: v1
kind: Secret
metadata:
    name: tns-csi-truenas-api-config
    namespace: kube-system
type: Opaque
stringData:
    api-key: ENC[AES256_GCM,data:yLv32+mPjX98fhgKQlwz0R67CjfTL+HqTExpSxH7EFkXHmeTS+uGDbBeIk3osIAGGEFTIjYRNvZnbMpK+iXTx5zk,iv:LaKYl3uqEsk8X12WUSi15GV3Nlp/PRi2xG0Az3hJF/E=,tag:syfi8DnPUo4SPSMmUgn8/A==,type:str]
    url: ENC[AES256_GCM,data:tgyVgPWDf0+FoLMpjbPVayZxI/ZlJDAh7MAOPf4dBfMVMMk=,iv:m7Wz1h4sHsKU5xpolhmOFYr416WiIfPYZhc50ELUOLU=,tag:fL0pDzmXzxGhbVDKVK1pcQ==,type:str]
sops:
    age:
        - recipient: age1jyccg37m4ya4hmjynme83ye58zktx9qhagqwn8rc6zmh27s58fdsvclvu0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUcXpNWFM1SGVkVEZpQlZh
            UnBQaHpJUGlYUFZwT0dseFBZWFlIdEkrOUc0CnZrc0ZveUdjL2tWeW8rUjVQRWJo
            SGxBZFdlczdWenVLVEdEMXE2VUxCOU0KLS0tIE5NQWVaWFY5YWpZbGlpVFpvbjF1
            SnFpYi9MTVpOeDVIUkc1OTJZUXRUTFUKre/RoNLelFgQzIX++qzyDOeQannJdFN6
            K2K+N6fbHeoj5RaC7AIYCalSUtVADE4zWgWd8/c/pEilFzSiHj7Tbw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1mg0cjjfnny5247jngl0hwwevyqgha3j4c6mhf5t9xucr6rl5qp2q334a22
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCaUdrWFM0N3FnNWh2Yk9M
            V3NjQlJqRVVpTWdNVzNLM3dLMFpmREphSEcwClBJazRGS0hxYm05YUZzRXRkeGVE
            UzRkb09VLzlmQ1dlVHNoVVE5bXB5dFEKLS0tIHRNR2NTazdaSlVjMjFjMXY3cGFw
            Q1luZUZvMlJYTi9TNkwyOGFUWDF0Q2cK1oEfvTd5cud2iton4GGsXRNnbfSL6nXm
            3XnuX7Wt2j6s0wAi3ojwLzPY3Jsrd4Un+J98OMdmd0i4drXdbUQ9pw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1t9tzynl3lvld2xagkety02s4pzfntfwtswtddnqzes07dwn7evqqzze6lf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0ZXpWbVpaSjU1SXNnSzZQ
            eXBZN2wxNEhiZXNqcHI3Z0NTOUhwK255MVNBCkdHd2l6MmJoMzlSMy9EYjlnakRh
            cmc2NGVVSlhGWldqak8vTmxnOVNpMUkKLS0tIENtZXprbUxrRmh3d0w3bTU1eldh
            aWNsQmNFUnJSaUIwQjNyVEtYa0NaK0UK88usLdImT9ZIcn4o7cBY+i/nqni0Hp3R
            IXwUlOo2HDmeNScPXyb/HYRjFK8yoa6JrvBXOYCf4N6E5wRl0GuhsQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T18:22:44Z"
    mac: ENC[AES256_GCM,data:m/OAvDEuznrl/tNdbHlsuIdGSAv5werREWIUI9QJ/DR2nb+/F35YFd0zOq191Vpey7/0BkjtDqGi+u70bpTzh/Ov27iAvoOJPvp7oLoHEWr+EFDIC59QPV96+vhBQ/TICDk/znq3U1XNYzV1JD/diLCUJrX2ZSolL5lb7KFXLhg=,iv:f1CsjQyxutlpNW+37SgLB17njeNkstjUmejnCewvFQA=,tag:+Rj6/iqjWoGUvwV9jsZkEw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
