apiVersion: ENC[AES256_GCM,data:Gwk=,iv:RpnShtMWAledGuYbOcIolVyyDp8UhuXeXB5YJqhFGhc=,tag:xuV9Jjpigo4uuRXrJjtjtw==,type:str]
kind: ENC[AES256_GCM,data:nqibxVwV,iv:ZLwce6XMJiH/hKw1LVUbxxrnBxJ9tOtg0wZcqtgq/MA=,tag:2q1b+0hY/4qeIxcN0iuA1g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:k3EIw5R4FLHJ2IgvBBIuv2wASWPoZVJhc/I=,iv:+2Qa3OQqZyBAOcSxBMdKpVKSlt6bkPAP49J0bNgiKDg=,tag:sHftt1RujxhJT9FI0bx+jg==,type:str]
    namespace: ENC[AES256_GCM,data:2ZhC48dfMttw9Xs=,iv:b61hdlzrBBnl0Dd3dsp6Tz0h6Yj/xG6Gb75e6r54Qpo=,tag:KmanIOqTSRP7bwKGCLJ4kA==,type:str]
type: ENC[AES256_GCM,data:EDzN52pd,iv:T72FcV/nxZ5VQdqa0gc93+zipLP2wMn4teSf47xxeoQ=,tag:6X/nGqDoF0s56QeZF6jXog==,type:str]
stringData:
    api-key: ENC[AES256_GCM,data:ITy3J8upu1NdqaUQybL1dlewt4ujkRjSffwpNvcTEZji5EvrFaMDlzSrYjnpW4oSQwejKAL8RElAdIaha5/TOutU,iv:YIMEXitw1kQAzp0Hf+ix8RfUWGLr3/ETcareJiW8iqI=,tag:7Vww875V9POoR6g3j/TQhQ==,type:str]
    url: ENC[AES256_GCM,data:dN/amiLlTkR80Vsz/0WPUWSIhtL1cw+u7OgJk+WfORh54pk=,iv:slH/ftH/WuWNRLmaJjYkZMgbkIco1oZmualyHy5NNmM=,tag:3+dm566adPU/nf1vOKbxGA==,type:str]
sops:
    age:
        - recipient: age1jyccg37m4ya4hmjynme83ye58zktx9qhagqwn8rc6zmh27s58fdsvclvu0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDRmhzZlVZSzBlNXBQWlcv
            R2QwM1BiM0dpZlVnZUYyeGlqcEFRY2o0NENVClRnRnZzMTQ4MTZoYk5QeDhiaHBw
            cXl2QnEycVlKYWJtU2RQeDRPb09MK00KLS0tIGxrclhIOVh3U0xhUDFjYkdsSDNU
            SEViTGtWbHU5aGNURW40ZzZpT2IwVmsKYktv/ORxHc7bTrzgHunnflyG2bZ67UQO
            3mk5Qgr6ie3D/q6+XTy2dy/2LVXppleXD2CqojOE84Om0PhVJjUd7w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1mg0cjjfnny5247jngl0hwwevyqgha3j4c6mhf5t9xucr6rl5qp2q334a22
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnS2RCRS9CajBocUhXZnlz
            bElEa1J1K3NaTTVldFlNTElvbThFL2VlS0VJCit6T3h0aFpnSVpYV3oyOWV2TW5s
            a3EvbEQyTDJnOURMTC91RTMyNnp6OHcKLS0tIGw2TmM1d0VKU2UzeC9mdXE2S1Rl
            SkttdXJKcHJvbzNGWk9HK0FsZzlLQmcKtj5c+CWhrhJsLQJRDgyaU4yhqyN0IgZX
            2kabSk0f/58al1INSg00+Y85Rq9ZqprGeKm6lV16fTfbGbxK1wiD/w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1t9tzynl3lvld2xagkety02s4pzfntfwtswtddnqzes07dwn7evqqzze6lf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByeWJGeVBmSGxtcUhaR0hG
            Q0laOXlGNFR2ckpTelN5a2FXekRGeGRzR0RZCk12R1NNUHRBaFpnUE10a0NMbjh1
            QzNYUVVkZGFnVEJlbGVZUlJWbnVhWU0KLS0tIGc1TEdvYXlJeUo5QWpTRFdETThJ
            QTBtRTZKSEV4Q1ltVm1YMXIyVHF3T0UKDuuJ1gTkkRuDuEwGwmWdtjFjvdddM/B2
            UrY/8h9aqNptQv7Eyr3lOY5EYS4oNuxzgLw8NC3ITD9xpwsNkEi5/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T18:07:19Z"
    mac: ENC[AES256_GCM,data:c0/gWGNnwtcfWbPqQprhQ7p4Q+9ab8wDYVGQ90oIDik849eSLfvsjnnvMm6WtlgKoeVmKmgIQP+WPs6ahSfpHiRH+k5ESuEOhynWd9L0Pvezj4r+qk1hfi7iI8H00als02aLTSIqjYKmqLvZsAXq9aqhbdTmWLZc6MfjR5Hfuqc=,iv:s0SS9E9OeE+yx7M65zvN8bxlcjXHcMrDWx/E4wLPNDc=,tag:AvxSBgam/f4rdR7ditS/Xg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
