apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library
  namespace: immich
spec:
  storageClassName: tns-csi-nvmeof
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
