name: Flux Diff on PR

on:
  pull_request:
    branches: [master]
    paths:
      - "k8s-manifests/**"

permissions:
  pull-requests: write
  contents: read

jobs:
  flux-diff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          path: pull

      - name: Checkout Master
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          ref: master
          path: master

      - name: Install Tools
        run: |
          pip install flux-local
          curl -s https://fluxcd.io/install.sh | sudo bash

      - name: Run Diff
        run: |
          flux-local diff ks --path pull/k8s-manifests --path-orig master/k8s-manifests -A --skip-secrets > raw_ks.txt || true
          flux-local diff hr --path pull/k8s-manifests --path-orig master/k8s-manifests -A --skip-secrets > raw_hr.txt || true

          clean_diff() {
            sed '/^[[:space:]]*$/d' "$1" | sed 's/^--- /\n--- /' > "$2"
          }

          clean_diff raw_ks.txt clean_ks.txt
          clean_diff raw_hr.txt clean_hr.txt

          echo "## ⛵ Flux Change Summary" > flux_diff.txt
          
          if grep -q '^[+-]' clean_ks.txt; then
            echo "### 🏗️ Kustomization Diffs" >> flux_diff.txt
            echo '```diff' >> flux_diff.txt
            cat clean_ks.txt >> flux_diff.txt
            echo -e '\n```\n' >> flux_diff.txt
            HAS_CHANGES=true
          fi

          if grep -q '^[+-]' clean_hr.txt; then
            echo "### 📦 HelmRelease Diffs" >> flux_diff.txt
            echo '```diff' >> flux_diff.txt
            cat clean_hr.txt >> flux_diff.txt
            echo -e '\n```' >> flux_diff.txt
            HAS_CHANGES=true
          fi

          if [ "$HAS_CHANGES" != "true" ]; then
            echo "✅ No changes detected in manifests or Helm values." >> flux_diff.txt
          fi
      - name: Post Comment
        uses: mshick/add-pr-comment@b8f338c590a895d50bcbfa6c5859251edc8952fc # v2
        with:
          message-id: flux-diff
          message-path: flux_diff.txt
          preformatted: false
